const PRODUCT = [
  {
    name: "iphone",
    price: 154,
    feature: true,
    company: "Apple",
  },
  {
    name: "iphone10",
    price: 1154,
    feature: true,
    company: "Apple",
  },
  {
    name: "watch",
    price: 204,
    company: "Apple",
  },
  {
    name: "watch10",
    price: 304,
    company: "Apple",
  },
  {
    name: "s20",
    price: 404,
    company: "Dell",
  },
  {
    name: "Dell gaming",
    price: 501,
    company: "Dell",
  },
  {
    name: "mi20",
    price: 701,
    company: "mi",
  },
  {
    name: "oppof1",
    price: 5004,
    company: "Oppo",
  },
  {
    name: "f1pro",
    price: 400,
    company: "Samsung",
  },
  {
    name: "Galaxy S21",
    price: 799,
    feature: true,
    company: "Samsung",
  },
  {
    name: "MacBook Pro",
    price: 1499,
    feature: true,
    company: "Apple",
  },
  {
    name: "Redmi Note 10",
    price: 249,
    feature: true,
    company: "Xiaomi",
  },
  {
    name: "Inspiron 15",
    price: 699,
    feature: true,
    company: "Dell",
  },
  {
    name: "OnePlus 9",
    price: 699,
    feature: true,
    company: "mi",
  },
  {
    name: "iPhone 11",
    price: 699,
    feature: true,
    company: "Apple",
  },
  {
    name: "Galaxy Watch 4",
    price: 299,
    feature: true,
    company: "Samsung",
  },
  {
    name: "Oppo Find X3",
    price: 799,
    feature: true,
    company: "Oppo",
  },
  {
    name: "Dell XPS 13",
    price: 1199,
    feature: true,
    company: "Dell",
  },
  {
    name: "Xiaomi Mi Band 6",
    price: 49,
    feature: true,
    company: "Xiaomi",
  },
  {
    name: "iPad Air",
    price: 499,
    feature: true,
    company: "Apple",
  },
  {
    name: "Samsung QLED TV",
    price: 1099,
    feature: true,
    company: "Samsung",
  },
  {
    name: "Dell Inspiron Laptop",
    price: 899,
    feature: true,
    company: "Dell",
  },
  {
    name: "Xiaomi Redmi Earbuds",
    price: 59,
    feature: true,
    company: "Xiaomi",
  },
  {
    name: "Oppo Reno 6 Pro",
    price: 699,
    feature: true,
    company: "Oppo",
  },
  {
    name: "Apple AirPods Pro",
    price: 249,
    feature: true,
    company: "Apple",
  },
  {
    name: "Dell Ultrasharp Monitor",
    price: 349,
    feature: true,
    company: "Dell",
  },
  {
    name: "Xiaomi Mi Notebook",
    price: 799,
    feature: true,
    company: "Xiaomi",
  },
  {
    name: "Samsung Galaxy Tab S7",
    price: 649,
    feature: true,
    company: "Samsung",
  },
  {
    name: "Apple Watch Series 7",
    price: 399,
    feature: true,
    company: "Apple",
  },
  {
    name: "Vivo X50",
    price: 399,
    feature: true,
    company: "Vivo",
  },
  {
    name: "Vivo V20",
    price: 299,
    feature: true,
    company: "Vivo",
  },
  {
    name: "POCO X3",
    price: 299,
    feature: true,
    company: "POCO",
  },
  {
    name: "Realme 7 Pro",
    price: getRandomPrice(10000, 25000),
    feature: true,
    company: "Realme",
  },
  {
    name: "OnePlus Nord 2",
    price: getRandomPrice(10000, 25000),
    feature: true,
    company: "OnePlus",
  },
  {
    name: "Motorola Moto G Power",
    price: getRandomPrice(10000, 25000),
    feature: true,
    company: "Motorola",
  },
  {
    name: "Nokia 5.4",
    price: getRandomPrice(10000, 25000),
    feature: true,
    company: "Nokia",
  },
  {
    name: "Realme C25",
    price: getRandomPrice(10000, 25000),
    feature: true,
    company: "Realme",
  },
  {
    name: "OnePlus 9",
    price: getRandomPrice(10000, 25000),
    feature: true,
    company: "OnePlus",
  },
  {
    name: "Motorola Edge+",
    price: getRandomPrice(10000, 25000),
    feature: true,
    company: "Motorola",
  },
  {
    name: "Nokia 8.3",
    price: getRandomPrice(10000, 25000),
    feature: true,
    company: "Nokia",
  },
  {
    name: "Realme Narzo 30 Pro",
    price: getRandomPrice(10000, 25000),
    feature: true,
    company: "Realme",
  },
  {
    name: "OnePlus 9 Pro",
    price: getRandomPrice(10000, 25000),
    feature: true,
    company: "OnePlus",
  },
  {
    name: "Motorola Moto G Stylus",
    price: getRandomPrice(10000, 25000),
    feature: true,
    company: "Motorola",
  },
  {
    name: "Nokia 6.2",
    price: getRandomPrice(10000, 25000),
    feature: true,
    company: "Nokia",
  },
  {
    name: "Realme 8",
    price: getRandomPrice(10000, 25000),
    feature: true,
    company: "Realme",
  },
  {
    name: "OnePlus 8T",
    price: getRandomPrice(10000, 25000),
    feature: true,
    company: "OnePlus",
  },
  {
    name: "Motorola Moto G Fast",
    price: getRandomPrice(10000, 25000),
    feature: true,
    company: "Motorola",
  },
  {
    name: "Nokia 2.4",
    price: getRandomPrice(10000, 25000),
    feature: true,
    company: "Nokia",
  },
  {
    name: "POCO F3",
    price: 499,
    feature: true,
    company: "POCO",
  },
  {
    name: "Infinix Hot 10",
    price: 149,
    feature: true,
    company: "Infinix",
  },
  {
    name: "Infinix Note 10",
    price: 199,
    feature: true,
    company: "Infinix",
  },
  {
    name: "Samsung Galaxy S21",
    price: 799,
    feature: true,
    company: "Samsung",
  },
  {
    name: "Samsung Galaxy A52",
    price: 349,
    feature: true,
    company: "Samsung",
  },
  {
    name: "Google Pixel 6",
    price: 699,
    feature: true,
    company: "Google",
  },
  {
    name: "Google Pixel 5a",
    price: 449,
    feature: true,
    company: "Google",
  },
  {
    name: "Sony Xperia 1 III",
    price: 1099,
    feature: true,
    company: "Sony",
  },
  {
    name: "Sony Xperia 5 II",
    price: 849,
    feature: true,
    company: "Sony",
  },
  {
    name: "Lenovo ThinkPad X1 Carbon",
    price: getRandomPrice(50000, 100000),
    feature: true,
    company: "Lenovo",
  },
  {
    name: "HP Spectre x360",
    price: getRandomPrice(50000, 100000),
    feature: true,
    company: "HP",
  },
  {
    name: "Dell XPS 13",
    price: getRandomPrice(50000, 100000),
    feature: true,
    company: "Dell",
  },
  {
    name: "ASUS ROG Strix Scar III",
    price: getRandomPrice(50000, 100000),
    feature: true,
    company: "ASUS",
  },
  {
    name: "ASUS ZenBook 14",
    price: getRandomPrice(50000, 100000),
    feature: true,
    company: "ASUS",
  },
  {
    name: "ASUS Vivobook S15",
    price: getRandomPrice(50000, 100000),
    feature: true,
    company: "Vivobook",
  },
  {
    name: "Lenovo Legion 5",
    price: getRandomPrice(50000, 100000),
    feature: true,
    company: "Lenovo",
  },
  {
    name: "HP Envy x360",
    price: getRandomPrice(50000, 100000),
    feature: true,
    company: "HP",
  },
  {
    name: "Dell Inspiron 14",
    price: getRandomPrice(50000, 100000),
    feature: true,
    company: "Dell",
  },
  {
    name: "ASUS VivoBook 15",
    price: getRandomPrice(50000, 100000),
    feature: true,
    company: "Vivobook",
  },
  {
    name: "Lenovo Yoga C940",
    price: getRandomPrice(50000, 100000),
    feature: true,
    company: "Lenovo",
  },
  {
    name: "HP Pavilion x360",
    price: getRandomPrice(50000, 100000),
    feature: true,
    company: "HP",
  },
  {
    name: "Dell XPS 15",
    price: getRandomPrice(50000, 100000),
    feature: true,
    company: "Dell",
  },
  {
    name: "ASUS TUF Gaming A15",
    price: getRandomPrice(50000, 100000),
    feature: true,
    company: "ASUS",
  },
  {
    name: "ASUS VivoBook Flip 14",
    price: getRandomPrice(50000, 100000),
    feature: true,
    company: "Vivobook",
  },
  {
    name: "Acer Predator Helios 300",
    price: getRandomPrice(60000, 90000),
    feature: true,
    company: "Acer",
  },
  {
    name: "Microsoft Surface Laptop 3",
    price: getRandomPrice(70000, 110000),
    feature: true,
    company: "Microsoft Surface series",
  },
  {
    name: "MSI GS66 Stealth",
    price: getRandomPrice(65000, 95000),
    feature: true,
    company: "MSI (Micro-Star International)",
  },
  {
    name: "Toshiba Portege X30L-G",
    price: getRandomPrice(50000, 80000),
    feature: true,
    company: "Toshiba",
  },
  {
    name: "Acer Aspire 5",
    price: getRandomPrice(35000, 60000),
    feature: true,
    company: "Acer",
  },
  {
    name: "Microsoft Surface Laptop 4",
    price: getRandomPrice(72000, 110000),
    feature: true,
    company: "Microsoft Surface series",
  },
  {
    name: "MSI Prestige 14",
    price: getRandomPrice(60000, 95000),
    feature: true,
    company: "MSI (Micro-Star International)",
  },
  {
    name: "Toshiba Tecra A40-G",
    price: getRandomPrice(52000, 82000),
    feature: true,
    company: "Toshiba",
  },
  {
    name: "Acer Swift 5",
    price: getRandomPrice(37000, 62000),
    feature: true,
    company: "Acer",
  },
  {
    name: "Microsoft Surface Laptop Go",
    price: getRandomPrice(68000, 105000),
    feature: true,
    company: "Microsoft Surface series",
  },
  {
    name: "MSI GS75 Stealth",
    price: getRandomPrice(70000, 105000),
    feature: true,
    company: "MSI (Micro-Star International)",
  },
  {
    name: "Toshiba Portege X20W-D",
    price: getRandomPrice(51000, 81000),
    feature: true,
    company: "Toshiba",
  },
  {
    name: "Acer Predator Helios 300",
    price: getRandomPrice(60000, 90000),
    feature: true,
    company: "Acer",
  },
  {
    name: "Microsoft Surface Laptop 3",
    price: getRandomPrice(70000, 110000),
    feature: true,
    company: "Microsoft Surface series",
  },
  {
    name: "MSI GS66 Stealth",
    price: getRandomPrice(65000, 95000),
    feature: true,
    company: "MSI (Micro-Star International)",
  },
  {
    name: "Toshiba Portege X30L-G",
    price: getRandomPrice(50000, 80000),
    feature: true,
    company: "Toshiba",
  },
  {
    name: "Acer Aspire 5",
    price: getRandomPrice(35000, 60000),
    feature: true,
    company: "Acer",
  },
  {
    name: "Microsoft Surface Laptop 4",
    price: getRandomPrice(72000, 110000),
    feature: true,
    company: "Microsoft Surface series",
  },
  {
    name: "MSI Prestige 14",
    price: getRandomPrice(60000, 95000),
    feature: true,
    company: "MSI (Micro-Star International)",
  },
  {
    name: "Toshiba Tecra A40-G",
    price: getRandomPrice(52000, 82000),
    feature: true,
    company: "Toshiba",
  },
  {
    name: "Acer Swift 5",
    price: getRandomPrice(37000, 62000),
    feature: true,
    company: "Acer",
  },
  {
    name: "Microsoft Surface Laptop Go",
    price: getRandomPrice(68000, 105000),
    feature: true,
    company: "Microsoft Surface series",
  },
  {
    name: "MSI GS75 Stealth",
    price: getRandomPrice(70000, 105000),
    feature: true,
    company: "MSI (Micro-Star International)",
  },
  {
    name: "Toshiba Portege X20W-D",
    price: getRandomPrice(51000, 81000),
    feature: true,
    company: "Toshiba",
  },
  {
    name: "Acer Nitro 5",
    price: getRandomPrice(55000, 90000),
    feature: true,
    company: "Acer",
  },
  {
    name: "Microsoft Surface Pro 7",
    price: getRandomPrice(75000, 115000),
    feature: true,
    company: "Microsoft Surface series",
  },
  {
    name: "MSI Modern 14",
    price: getRandomPrice(59000, 93000),
    feature: true,
    company: "MSI (Micro-Star International)",
  },
  {
    name: "Toshiba Satellite Pro",
    price: getRandomPrice(48000, 78000),
    feature: true,
    company: "Toshiba",
  },
  {
    name: "Acer Swift 3",
    price: getRandomPrice(38000, 65000),
    feature: true,
    company: "Acer",
  },
  {
    name: "Microsoft Surface Book 3",
    price: getRandomPrice(79000, 120000),
    feature: true,
    company: "Microsoft Surface series",
  },
  {
    name: "MSI Creator 17",
    price: getRandomPrice(72000, 110000),
    feature: true,
    company: "MSI (Micro-Star International)",
  },
  {
    name: "Toshiba Dynabook Portege",
    price: getRandomPrice(54000, 88000),
    feature: true,
    company: "Toshiba",
  },
];

function getRandomPrice(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

module.exports = { PRODUCT };
